
production:
  adapter: postgresql
  database: foo_production
  pool: 100

development:
  adapter: postgresql
  database: foo_development
#  host: localhost
#  port: 5432
  pool: 100

test: &test
  adapter: postgresql
  database: foo_test
  pool: 100

cucumber:
  <<: *test

